export const GET_MOVIES = "GET_MOVIES";
export const GET_DETAILS = "GET_DETAILS";
export const ADD_MOVIE_FAVORITE = "ADD_MOVIE_FAVORITE";
export const REMOVE_MOVIE_FAVORITE = "REMOVE_MOVIE_FAVORITE";
