const INCREMENTO = 'INCREMENTO';
const DECREMENTO = 'DECREMENTO';
const INCREMENTOIMPAR = 'INCREMENTOIMPAR'
// const INCREMENTOASINCRONICO = 'INCREMENTOASINCRONICO'

module.exports = {
  INCREMENTO,
  DECREMENTO,
  INCREMENTOIMPAR,
  // INCREMENTOASINCRONICO
}